use crate::types::*;

/// Generate Rust source code from parsed schemas.
pub fn generate(schemas: &[Schema]) -> String {
    let mut output = String::new();

    output.push_str("// This file is auto-generated by the revolut-codegen tool.\n");
    output.push_str("// Do not edit manually.\n\n");
    output.push_str("#![allow(clippy::all)]\n\n");
    output.push_str("use serde::{Deserialize, Serialize};\n\n");

    for schema in schemas {
        match &schema.kind {
            SchemaKind::Struct(struct_def) => {
                emit_struct(&mut output, &schema.name, struct_def);
            }
            SchemaKind::Enum(enum_def) => {
                emit_enum(&mut output, &schema.name, enum_def);
            }
            SchemaKind::TypeAlias(ty) => {
                output.push_str(&format!("pub type {} = {};\n\n", schema.name, ty));
            }
            SchemaKind::StringNewtype => {
                // Skip — plain string types don't need a separate type
            }
        }
    }

    output
}

fn emit_struct(output: &mut String, name: &str, def: &StructDef) {
    // Check if this is a HashMap wrapper (single _additional field)
    if def.fields.len() == 1 && def.fields[0].name == "_additional" {
        if let FieldType::HashMap(inner) = &def.fields[0].ty {
            output.push_str(&format!(
                "pub type {} = std::collections::HashMap<String, {}>;\n\n",
                name,
                inner.to_rust_type()
            ));
            return;
        }
    }

    output.push_str("#[derive(Clone, Debug, Deserialize, Serialize)]\n");
    output.push_str(&format!("pub struct {} {{\n", name));

    for field in &def.fields {
        // Emit serde attributes
        let mut attrs = Vec::new();

        if let Some(rename) = &field.serde_rename {
            attrs.push(format!("rename = \"{}\"", rename));
        }

        if !field.required {
            if matches!(&field.ty, FieldType::Option(_)) {
                attrs.push("skip_serializing_if = \"Option::is_none\"".to_string());
            }
        }

        if !attrs.is_empty() {
            output.push_str(&format!("    #[serde({})]\n", attrs.join(", ")));
        }

        output.push_str(&format!(
            "    pub {}: {},\n",
            field.rust_name,
            field.ty.to_rust_type()
        ));
    }

    output.push_str("}\n\n");
}

fn emit_enum(output: &mut String, name: &str, def: &EnumDef) {
    if def.is_complex || def.is_untagged {
        // Complex enum with typed variants (oneOf)
        output.push_str("#[derive(Clone, Debug, Deserialize, Serialize)]\n");
        output.push_str("#[serde(untagged)]\n");
        output.push_str(&format!("pub enum {} {{\n", name));

        for variant in &def.complex_variants {
            output.push_str(&format!(
                "    {}({}),\n",
                variant.name,
                variant.ty.to_rust_type()
            ));
        }

        output.push_str("}\n\n");
        return;
    }

    // Simple string enum
    output.push_str("#[derive(Clone, Debug, Deserialize, Serialize)]\n");

    if let Some(rename_all) = &def.rename_all {
        output.push_str(&format!("#[serde(rename_all = \"{}\")]\n", rename_all));
    }

    output.push_str(&format!("pub enum {} {{\n", name));

    for variant in &def.variants {
        // Check if we need per-variant rename
        let needs_rename = if def.rename_all.is_some() {
            // Check if the variant name roundtrips correctly with the rename_all
            let expected = match def.rename_all.as_deref() {
                Some("snake_case") => to_snake_case_value(&variant.name),
                Some("SCREAMING_SNAKE_CASE") => to_screaming_snake_case_value(&variant.name),
                Some("PascalCase") => variant.name.clone(),
                Some("camelCase") => to_camel_case_value(&variant.name),
                _ => variant.original.clone(),
            };
            expected != variant.original
        } else {
            true
        };

        if needs_rename {
            output.push_str(&format!("    #[serde(rename = \"{}\")]\n", variant.original));
        }
        output.push_str(&format!("    {},\n", variant.name));
    }

    output.push_str("}\n\n");
}

fn to_snake_case_value(pascal: &str) -> String {
    heck::ToSnakeCase::to_snake_case(pascal)
}

fn to_screaming_snake_case_value(pascal: &str) -> String {
    heck::ToShoutySnakeCase::to_shouty_snake_case(pascal)
}

fn to_camel_case_value(pascal: &str) -> String {
    heck::ToLowerCamelCase::to_lower_camel_case(pascal)
}
